repos:
 - repo: https://github.com/Quantco/pre-commit-mirrors-black
   rev: 22.3.0
   hooks:
     - id: black-conda
       args:
         - --safe
         - --target-version=py36
 - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
   rev: 4.0.1
   hooks:
    - id: flake8-conda
